server:
  port: 8443

springdoc:
  show-actuator: false
  packages-to-scan: com.kaishui.entitlement
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/entitlement
management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all endpoints
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:your_default_dev_password}
    algorithm: PBEWITHHMACSHA512ANDAES_256

ad:
  group:
    suffix:
      admin: "-ADMIN"
      manager: "-MANAGER"
      user: "-USER"
    prefi: "AD-"
jwt:
  public:
    key: ""