### get all users
GET {{url}}/api/users
Accept: application/json

###CREATE USER
POST {{url}}/api/users
Accept: application/json
Content-Type: application/json
Authorization: TestUser1

{
  "username": "testuser2",
  "email": "test@example.com",
  "staffId": "12345"
}

### Get User by ID:
GET {{url}}/api/users/67f61a7843061a4183cc97eb
Accept: application/json

### UPDATE USERxxx
PUT {{url}}/api/users
Accept: application/json
Authorization: Basic user passwd
Content-Type: application/json

{
  "id": "67f61a7843061a4183cc97eb",
  "username": "updateduser",
  "staffId": "12345",
  "email": "updated@example.com"
}

###
DELETE {{url}}/api/users/67f4df4bd1dd833d80b70db7
Accept: application/json

###
### Get User role
GET {{url}}/api/users/current/role?userCase=ABC
Accept: application/json




